version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
  database:
    image: postgres:14.1-alpine
    container_name: practice-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password0701
      - POSTGRES_DB=practice
    ports:
      - '5432:5432/tcp'

  service:
    build: .
    container_name: practice_server
    ports:
        - '8079:8079'
        - '9911:9911'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
