version: "3.8"
#https://github:
#  com/vegasbrianc/prometheus/tree/master/alertmanager:https://github.com/vegasbrianc/prometheus/tree/master/alertmanager
services:
#  database:
#    image: postgres:14.1-alpine
#    container_name: practice-db
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password0701
#      - POSTGRES_DB=practice
#    ports:
#      - '5432:5432/tcp'
#
#  service:
#    build: .
#    container_name: practice_server
#    ports:
#      - '8079:8079'
#      - '9911:9911'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.3.0
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
#      - grafana:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro'

  cadvisor:
    # TODO: latest tag is not updated, check latest release https://github.com/google/cadvisor/releases
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    ports:
      - "9192:9192"
#    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true