version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"

  service:
    build: .
    container_name: practice_server
    ports:
        - '8079:8079'
        - '9911:9911'